# Generated by Django 2.2.6 on 2019-11-15 23:19

import customadmin.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_angkatan', models.CharField(max_length=50)),
                ('tahun', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), customadmin.models.yearchoice])),
            ],
            options={
                'verbose_name_plural': 'Angkatan',
                'db_table': 'tb_angkatan',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
                'db_table': 'tb_kelas',
            },
        ),
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kuis', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.Kelas')),
            ],
            options={
                'verbose_name_plural': 'Kuis',
                'db_table': 'tb_kuis',
            },
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id_pelajaran', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelajaran', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pelajaran',
                'db_table': 'tb_pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id_soal', models.AutoField(primary_key=True, serialize=False)),
                ('soal', models.TextField()),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('benar', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='a', max_length=1)),
                ('pelajaran', models.ForeignKey(db_column='id_pelajaran', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Soal',
                'db_table': 'tb_soal',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nama_bapak', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('sekolah', models.CharField(max_length=100)),
                ('alamat_sekolah', models.TextField()),
                ('level', models.CharField(choices=[('Siswa', 'Siswa')], default='Siswa', max_length=20)),
                ('angkatan', models.ForeignKey(db_column='angkatan', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Angkatan')),
                ('kelas', models.ForeignKey(db_column='kelas', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Kelas')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
                'db_table': 'tb_siswa',
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id_nilai', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('kuis', models.ForeignKey(db_column='id_kuis', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Kuis')),
                ('nama', models.ForeignKey(db_column='id_profil', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Siswa')),
            ],
            options={
                'verbose_name_plural': 'Nilai',
                'db_table': 'tb_nilai',
            },
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id_materi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_materi', models.CharField(max_length=50)),
                ('File_Pdf', models.FileField(blank=True, null=True, upload_to='materi/')),
                ('status', models.BooleanField(default=False)),
                ('pelajaran', models.ForeignKey(db_column='id_pelajaran', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Materi',
                'db_table': 'tb_materi',
            },
        ),
        migrations.AddField(
            model_name='kuis',
            name='pelajaran',
            field=models.ForeignKey(db_column='id_pelajaran', on_delete=django.db.models.deletion.CASCADE, to='customadmin.Pelajaran'),
        ),
        migrations.AddField(
            model_name='kuis',
            name='soal',
            field=models.ManyToManyField(db_column='id_soal', to='customadmin.Soal'),
        ),
    ]
