# Generated by Django 2.2.6 on 2019-11-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='File_Pdf',
            field=models.FileField(blank=True, null=True, upload_to='materi'),
        ),
    ]
