# Generated by Django 2.2.6 on 2019-11-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_auto_20191117_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuis',
            name='soal',
            field=models.ManyToManyField(db_column='id_soal', to='customadmin.Soal', verbose_name='Soal'),
        ),
    ]
